from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Mapping, Sequence


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def as_text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text if text else default


def yaml_string(value: Any) -> str:
    text = as_text(value)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_frontmatter(
    document: Mapping[str, Any],
    summary_artifact: Mapping[str, Any] | None,
    *,
    exported_at: str,
) -> str:
    summary = summary_artifact or {}
    source_content_hash = as_text(summary.get("source_content_hash"), as_text(document.get("content_hash")))

    lines = [
        "---",
        'source: "local-ai-workbench"',
        'type: "document_summary"',
        f'exported_at: {yaml_string(exported_at)}',
        f'document_id: {yaml_string(document.get("id"))}',
        f'title: {yaml_string(document.get("title"))}',
        f'relative_path: {yaml_string(document.get("relative_path"))}',
        f'file_type: {yaml_string(document.get("file_type"))}',
        f'source_content_hash: {yaml_string(source_content_hash)}',
        f'summary_id: {yaml_string(summary.get("id"))}',
        f'summary_method: {yaml_string(summary.get("method"))}',
        "tags:",
        "  - local-ai-workbench",
        "  - document-summary",
        "---",
    ]
    return "\n".join(lines)


def build_audit_section(audit_events: Sequence[Mapping[str, Any]]) -> str:
    if not audit_events:
        return "- No audit events provided."

    lines = []
    for event in audit_events:
        event_type = as_text(event.get("event_type"), "unknown_event")
        created_at = as_text(event.get("created_at"), "unknown_time")
        lines.append(f"- `{created_at}` — `{event_type}`")
    return "\n".join(lines)


def build_obsidian_document_summary_markdown(
    document: Mapping[str, Any],
    summary_artifact: Mapping[str, Any] | None = None,
    *,
    audit_events: Sequence[Mapping[str, Any]] | None = None,
    exported_at: str | None = None,
) -> str:
    export_timestamp = exported_at or utc_now_iso()
    title = as_text(document.get("title"), "Untitled document")
    relative_path = as_text(document.get("relative_path"), "unknown path")
    file_type = as_text(document.get("file_type"), "unknown")
    content_hash = as_text(document.get("content_hash"), "unknown")
    scanned_at = as_text(document.get("scanned_at"), "unknown")

    summary = summary_artifact or {}
    summary_text = as_text(summary.get("summary_text"), "No summary artifact provided.")
    summary_created_at = as_text(summary.get("created_at"), "unknown")
    summary_method = as_text(summary.get("method"), "not_available")

    frontmatter = build_frontmatter(document, summary_artifact, exported_at=export_timestamp)
    audit_section = build_audit_section(audit_events or [])

    sections = [
        frontmatter,
        "",
        f"# {title}",
        "",
        "## Source Document",
        "",
        f"- Relative path: `{relative_path}`",
        f"- File type: `{file_type}`",
        f"- Content hash: `{content_hash}`",
        f"- Scanned at: `{scanned_at}`",
        "",
        "## Summary",
        "",
        summary_text,
        "",
        "## Summary Metadata",
        "",
        f"- Method: `{summary_method}`",
        f"- Created at: `{summary_created_at}`",
        "",
        "## Audit Context",
        "",
        audit_section,
        "",
        "## Workbench Note",
        "",
        "This note was generated by Local AI Workbench as a one-way Markdown export preview.",
        "It does not modify the original source document.",
    ]

    return "\n".join(sections).strip() + "\n"
